# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8002

# mybatis
mybatis:
  mapper-locations: classpath*:com/york/**/mapper/*.xml
  type-aliases-package: org.csrp.cloud.entity